services:
  - type: web
    name: hockey-movies-proxy
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: API_KEY
        sync: false
